version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - "43306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: debug_on_docker_dev
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails_password

  web:
    build: .
    # command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/bash -c "rm -f tmp/pids/server.pid"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/var/www/debug_on_docker
    ports:
      - "14000:3000"
      - "1234:1234"
    depends_on:
      - db

volumes:
  db-data: